version: "3.9"
services:

  spring-api-image:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: users
      MYSQL_USER: darkus
      MYSQL_PASSWORD: 1999
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume:

#Debido a que el usuario no tenia privlegios para acceder a la base de datos se opto por configurarlo en la terminal
#de este contenedor:

#mysql -u root -p12345
#GRANT ALL PRIVILEGES ON users.* TO 'darkus'@'%';
#FLUSH PRIVILEGES;

#Por si la base de datos no existe
#SHOW DATABASES;
#CREATE DATABASE users;
#USE users;